package datastructure;

import java.awt.Graphics;
import java.awt.Color;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.JOptionPane;
public class TreeFrame extends javax.swing.JFrame {
     private int x;
     private int y;
     private int px;
     private int py;
     private int info;
     private int color;
     private int pcolor;
     LinkedList l;
    
    /** Creates new form TreeFrame */
    public TreeFrame() {
         l = new LinkedList();
         initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Red Black Tree");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Display");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1001, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 402, Short.MAX_VALUE)
        );

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(53, 53, 53)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(109, 109, 109)
                .add(jButton1)
                .add(152, 152, 152)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 171, Short.MAX_VALUE)
                .add(jButton3)
                .add(143, 143, 143)
                .add(jButton4)
                .add(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4)
                    .add(jButton3)
                    .add(jButton2)
                    .add(jButton1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AboutRBT a = new AboutRBT();
        a.setVisible(true);        
        a.setLocationRelativeTo( null );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        l.clear();
        repaint();
        Btree.root = Btree.sentinal;
        jTextField1.grabFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
     if(Btree.root == Btree.sentinal)
	    JOptionPane.showMessageDialog(null, "Tree Empty!");  
     else
     {
            int e = Integer.valueOf( jTextField1.getText() ).intValue(); 
            RBtree q = RBtree.root.Search(e);
            if(q==Btree.sentinal)
                JOptionPane.showMessageDialog(null, "Not Found!");
            else
            {
                RBtree y = q.DeleteNode();                
                l.remove(y);
                repaint();
            }
      }              
      jTextField1.setText("");  
      jTextField1.grabFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       if(Btree.root == Btree.sentinal)
            JOptionPane.showMessageDialog(null, "Tree Empty!");  
       else
       {
            int e = Integer.valueOf( jTextField1.getText() ).intValue(); 
            RBtree snode = RBtree.root.Search(e);
            if(snode==Btree.sentinal)
                JOptionPane.showMessageDialog(null, "Not Found!");
            else
            {
                int scolor = snode.getcolor();
                snode.setcolor(3);
                repaint();  
                JOptionPane.showMessageDialog(null, "Found!"); 
                snode.setcolor(scolor);
                repaint();
            }      
       }              
       jTextField1.setText("");
       jTextField1.grabFocus();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void paint(Graphics g)
    {
        g.setColor(Color.WHITE);        
        g.fillRect(20,90,1020,390);
        
        ListIterator i = l.listIterator();        
        while(i.hasNext())
        {
            RBtree q = (RBtree) i.next();
            x = q.getx();
            y = q.gety();
            px = q.getpx();
            py = q.getpy();
            info = q.info;
            color = q.getcolor();  
            pcolor = q.getpcolor();
            
            g.setColor(Color.BLACK);
            if(px!=0 && py !=0)
                g.drawLine(x+25/2,y+25/2,px+25/2,py+25/2);

            if(color==1)
                 g.setColor(Color.BLACK);
            else if(color == 2)
                     g.setColor(Color.RED);
                else
                     g.setColor(Color.GREEN);

            g.fillOval(x,y,25,25);
            if(px!=0 && py !=0)
            {    
                 if(pcolor==1)
                     g.setColor(Color.BLACK);
                 else if(pcolor == 2)
                         g.setColor(Color.RED);
                     else
                         g.setColor(Color.GREEN);
                 
                g.fillOval(px,py,25,25);    
                
                g.setColor(Color.WHITE);
                if(q.getparent().info>9)
                    g.drawString(Integer.toString(q.getparent().info),px+5,py+17);
                else
                    g.drawString(Integer.toString(q.getparent().info),px+8,py+17);
            }
            g.setColor(Color.WHITE);
            if(info>9)
                g.drawString(Integer.toString(info),x+5,y+17);
            else
                g.drawString(Integer.toString(info),x+8,y+17);   
        }       
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    int e = Integer.valueOf( jTextField1.getText() ).intValue();
    jTextField1.setText("");
    if(e<1 || e>99)
    {
        JOptionPane.showMessageDialog(null, "Insert between 1 and 99!.");
        jTextField1.grabFocus();
        return;
    }
    
    if(Btree.root == null)                                  /* Start of Program */
    {
        Btree.sentinal = new RBtree(0,null);  
        Btree.root = new RBtree(e, Btree.sentinal);
        Btree.root.InsertFixup(Btree.root);
        l.add(Btree.root);
        repaint();
    }
    else if(Btree.root == Btree.sentinal)                         /* Tree Empty */
    {
        Btree.root = new RBtree(e, Btree.sentinal);
        Btree.root.InsertFixup(Btree.root);
        l.add(Btree.root);
        repaint();
    }      
    else
    {
	RBtree q = Btree.root.Insert(e);	
        if (q==null)
        {
            JOptionPane.showMessageDialog(null, "Duplicate Value!.");
            jTextField1.grabFocus();
            return;
        }
        l.add(q);
        repaint();
    } 
    
    jTextField1.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TreeFrame f = new TreeFrame();
                f.setVisible(true); 
                f.setLocationRelativeTo( null );
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
